### ISSUE TITLE
how different ideas and performance from other rule based machine learning packages 

### ISSUE THREAD

**Issue by Sandy4321** [ferryjul/fairCORELS#2]
how different ideas and performance from other rule based machine learning packages 
arulesViz
arulesExplain
arules
arc
 arulesCBA  https://journal.r-project.org/archive/2019/RJ-2019-048/RJ-2019-048.pdf
 rCBA
EasyMiner
LISp-Miner desktop-based  implementation  of  the  GUHA  
rsubgroup  
Vikamine
https://github.com/fingoldin/pycorels  
https://github.com/lukassykora/actionrules
https://github.com/jirifilip/pyIDS
https://github.com/csinva/interpretability-implementations-demos/tree/master/imodels/bayesian_rule_lists

sorry for too complicated question ....

**Comment by Sandy4321** [comment]
also it would be interesting to run your code vs  pyARC
all algorithms 
M1      M1Algorithm,
    
M2 M2Algorithm
http://ceur-ws.org/Vol-2204/paper6.pdf
and QCBA
https://github.com/jirifilip/pyARC/blob/master/notebooks/qcba_extension/QCBA_benchmark.ipynb

by use 
data from 
https://github.com/fingoldin/pycorels/tree/master/examples/data

**Comment by ferryjul** [comment]
Thank you for your interest in fairCORELS !

Concerning the comparison with fairCORELS, the different models cited in your question do not deal with bias mitigation and thus should not directly be compared with fairCORELS.

**Comment by Sandy4321** [comment]
Looks interesting
May you share some links to description
How this bias mitigation happen?
And hopefully you do have code examples

**Comment by gbip** [comment]
> How this bias mitigation happen?

You should take a look at [this](https://arxiv.org/abs/1909.03977) paper on arxiv which is the publication associated with this project. Please correct me @ferryjul if I am wrong.
