### ISSUE TITLE
How different this from Corels?

### ISSUE THREAD

**Issue by Sandy4321** [ferryjul/fairCORELS#3]
How different this from Corels?
And previous Corels Python implementation?
Can you share some algorithm description
For example link to papers?

**Comment by ferryjul** [comment]
Hello, thank you for your interest in FairCORELS, and sorry for the late answer!

Our code is based on the CORELS Python binding (https://github.com/corels/pycorels), which is itself based on the original CORELS C++ implementation (https://github.com/corels/corels).

In a nutshell, the original CORELS algorithm aims at finding rule list r minimizing the sum of misclassification error and a sparsity regularization parameter. 

FairCORELS looks for a rule list minimizing the same objective function, subject to a given statistical fairness constraint. In other words, it implements an epsilon-constraint method to integrate fairness as a second objective.

Description of the algorithm and experiments can be found in the following paper: https://arxiv.org/pdf/1909.03977.pdf
